# Generated by Django 3.1.3 on 2020-11-25 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_count', models.IntegerField()),
                ('model', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled', models.BooleanField(default=False)),
                ('order_item_uid', models.UUIDField(default=uuid.uuid4)),
                ('order_uid', models.UUIDField(default=uuid.uuid4)),
                ('item_id', models.IntegerField()),
            ],
        ),
    ]
