# Generated by Django 3.1.3 on 2020-11-25 21:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=120, verbose_name='Комментарий')),
                ('item_uid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(max_length=60, verbose_name='status')),
                ('warranty_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
